springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
